/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.EstilosDAO;
import dao.MarcaDAO;
import dao.ModeloDAO;
import dao.OficinaDAO;
import entities.Oficina;
import static gui.RentaVehiculo.cal;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jenni
 */
public class RentaVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form RentaVehiculo
     */
    int adicionales;
    SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
    public static DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    public static Date date = new Date();
    public static Calendar cal = Calendar.getInstance();
    Date fechaRe;
    Date fechaDe;
    ArrayList modelos = new ArrayList();
    ArrayList marcas = new ArrayList();
    ArrayList estilo = new ArrayList();
    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public Class getColumnClass(int indiceColumna) {
            Object ima = getValueAt(0, indiceColumna);
            if (ima == null) {
                return Object.class;
            } else {
                return ima.getClass();
            }

        }
    };

    public RentaVehiculo() {
        initComponents();
        this.getContentPane().setBackground(Color.gray);
        this.setTitle("RENTA VEHICULOS");
        this.setLocationRelativeTo(null);
        cargarOficina();
        cargarMarcas();
        cargarModelos();
        cargarEstilo();

        ImageIcon icono = new ImageIcon(getClass().getResource("/image/usuario.png"));

        ImageIcon ponerImagen = new ImageIcon(icono.getImage().getScaledInstance(70, 100, 10));

        modelo.addColumn("Imagen", new Object[]{ponerImagen});
        modelo.addColumn("Nombre", new Object[]{"jenni"});
        tabla.setRowHeight(100);
        this.tabla.setModel(modelo);
        txtAño.setVisible(false);
        cal.add(Calendar.YEAR, +2000);//2000 year after
        Date min = cal.getTime();
        Date max = new Date();//actual date
        jDateRetiro.setSelectableDateRange(max, min);
        jDateDevol.setSelectableDateRange(max, min);
    }

    public void adicionales() {
        int adi = 0;
        if (rbtGps.isSelected()) {
            adi = adi + 9;
        }
        if (rbtBooster.isSelected()) {
            adi = adi + 11;
        }
        if (rbtSilla.isSelected()) {
            adi = adi + 3;
        }
        adicionales = adi;

    }

    public void filtro() {

    }

    public void cargarOficina() {
        OficinaDAO dao = new OficinaDAO();
        LinkedList<Oficina> oficinas = dao.cargarTodo();
        for (Oficina oficina : oficinas) {
            CbxOfiRetiro.addItem(oficina.getNombre());
            CbxOfiDevol.addItem(oficina.getNombre());
        }
    }

    public void cargarModelos() {
        ModeloDAO modelo1 = new ModeloDAO();
        modelos = modelo1.cargarModelo();
        for (int x = 0; x < modelos.size(); x++) {
            cbxModelo.addItem(modelos.get(x).toString());
        }
    }

    public void cargarMarcas() {
        MarcaDAO marca = new MarcaDAO();
        marcas = marca.cargarMarcas();
        for (int x = 0; x < marcas.size(); x++) {
            cbxMarca.addItem(marcas.get(x).toString());
        }
    }

    public void cargarEstilo() {
        EstilosDAO esti = new EstilosDAO();
        estilo = esti.cargarEstilos();
        for (int x = 0; x < estilo.size(); x++) {
            cbxEstilo.addItem(estilo.get(x).toString());
        }

    }

    public void obtenerCantDias() {
        int dias = -1;
        if (jDateRetiro.getDate() != null && jDateDevol.getDate() != null) {
            Calendar fecha_inicio = jDateRetiro.getCalendar();
            Calendar fecha_final = jDateDevol.getCalendar();
            while (fecha_inicio.before(fecha_final) || fecha_inicio.equals(fecha_final)) {
                dias++;
                fecha_inicio.add(Calendar.DATE, 1);
            }
            txtPrecio.setText("dias: " + dias);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione las fechas", "Calcular Dias", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CbxOfiRetiro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateDevol = new com.toedter.calendar.JDateChooser();
        jDateRetiro = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        CbxOfiDevol = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rbtGps = new javax.swing.JRadioButton();
        rbtBooster = new javax.swing.JRadioButton();
        rbtSilla = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rbtAño = new javax.swing.JRadioButton();
        rbtPrecio = new javax.swing.JRadioButton();
        rbtMarca = new javax.swing.JRadioButton();
        rbtModelo = new javax.swing.JRadioButton();
        txtAño = new javax.swing.JTextField();
        rbttransmision = new javax.swing.JRadioButton();
        rbtEstilo = new javax.swing.JRadioButton();
        txtPrecio = new javax.swing.JTextField();
        cbxMarca = new javax.swing.JComboBox<>();
        cbxEstilo = new javax.swing.JComboBox<>();
        cbxModelo = new javax.swing.JComboBox<>();
        cbxTransmi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.darkGray), null));

        jLabel1.setText("Oficina de retiro:");

        jLabel2.setText("Fecha de retiro:");

        jLabel3.setText("Fecha de devolución:");

        jLabel4.setText("Oficina de devolucion:");

        CbxOfiDevol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxOfiDevolActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5:00 am", "5:15 am", "5:30 am", "5:45 am", "6:00 am", "6:15 am", "6:30 am", "6:45 am", "7:00 am", "7:15 am", "7:30 am", "7:45 am", "8:00 am", "8:15 am", "8:30 am", "8:45 am", "9:00 am", "9:15 am", "9:30 am", "9:45 am", "10:00 am", "10:15 am", "10:30 am", "10:45 am", "11:00 am", "11:15 am", "11:30 am", "11:45 am", "12:00 pm", "12:15 pm", "12:30 pm", "12:45 pm", "1:00 pm", "1:15 pm", "1:30 pm", "1:45 pm", "2:00 pm", "2:15 pm", "2:30 pm", "2:45 pm", "3:00 pm", "3:15 pm", "3:30 pm", "3:45 pm", "4:00 pm", "4:15 pm", "4:30 pm", "4:45 pm", "5:00 pm", "5:15 pm", "5:30 pm", "5:45 pm", "6:00 pm", "6:15 pm", "6:30 pm", "6:45 pm", "7:00 pm", "7:15 pm", "7:30 pm", "7:45 pm", "8:00 pm", "8:15 pm", "8:30 pm", "8:45 pm", "9:00 pm", "9:15 pm", "9:30 pm", "9:45 pm", "10:00 pm" }));

        jLabel5.setText("Hora de retiro:");

        jLabel6.setText("Hora de devolución :");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5:00 am", "5:15 am", "5:30 am", "5:45 am", "6:00 am", "6:15 am", "6:30 am", "6:45 am", "7:00 am", "7:15 am", "7:30 am", "7:45 am", "8:00 am", "8:15 am", "8:30 am", "8:45 am", "9:00 am", "9:15 am", "9:30 am", "9:45 am", "10:00 am", "10:15 am", "10:30 am", "10:45 am", "11:00 am", "11:15 am", "11:30 am", "11:45 am", "12:00 pm", "12:15 pm", "12:30 pm", "12:45 pm", "1:00 pm", "1:15 pm", "1:30 pm", "1:45 pm", "2:00 pm", "2:15 pm", "2:30 pm", "2:45 pm", "3:00 pm", "3:15 pm", "3:30 pm", "3:45 pm", "4:00 pm", "4:15 pm", "4:30 pm", "4:45 pm", "5:00 pm", "5:15 pm", "5:30 pm", "5:45 pm", "6:00 pm", "6:15 pm", "6:30 pm", "6:45 pm", "7:00 pm", "7:15 pm", "7:30 pm", "7:45 pm", "8:00 pm", "8:15 pm", "8:30 pm", "8:45 pm", "9:00 pm", "9:15 pm", "9:30 pm", "9:45 pm", "10:00 pm" }));

        jLabel7.setText("Articulos Adicionales:");

        rbtGps.setText("GPS $9");
        rbtGps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGpsActionPerformed(evt);
            }
        });

        rbtBooster.setText("Booster $11");
        rbtBooster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtBoosterActionPerformed(evt);
            }
        });

        rbtSilla.setText("Silla de bebé $3 ");
        rbtSilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSillaActionPerformed(evt);
            }
        });

        jLabel8.setText("Filtro de búsqueda:");

        jButton1.setText("Buscar Vehículo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rbtAño.setText("Año");
        rbtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAñoActionPerformed(evt);
            }
        });

        rbtPrecio.setText("Precio");
        rbtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPrecioActionPerformed(evt);
            }
        });

        rbtMarca.setText("Marca");
        rbtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMarcaActionPerformed(evt);
            }
        });

        rbtModelo.setText("Modelo");
        rbtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtModeloActionPerformed(evt);
            }
        });

        rbttransmision.setText("Transmisión");
        rbttransmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbttransmisionActionPerformed(evt);
            }
        });

        rbtEstilo.setText("Estilo");
        rbtEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEstiloActionPerformed(evt);
            }
        });

        cbxTransmi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatica", "Manual" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(CbxOfiRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateDevol, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbxOfiDevol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(rbtGps)
                            .addComponent(rbtBooster)
                            .addComponent(rbtSilla)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbttransmision)
                                    .addComponent(rbtModelo)
                                    .addComponent(rbtEstilo)
                                    .addComponent(rbtMarca))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxEstilo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxTransmi, 0, 102, Short.MAX_VALUE)
                                    .addComponent(cbxMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtAño)
                                    .addComponent(rbtPrecio))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CbxOfiRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(CbxOfiDevol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateDevol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtGps)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtBooster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtSilla)
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtMarca)
                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtEstilo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbttransmision)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(cbxTransmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        //jDateDevol.getDateEditor().addPropertyChangeListener(new PropertyChangeListener(){
            //   public void propertyChange(PropertyChangeEvent evt){
                //    try{
                    //        verFechaDevolu();
                    //   }catch(Exception e){

                    //   }
                //    }
            //});
    //jDateRetiro.getDateEditor().addPropertyChangeListener(new PropertyChangeListener(){
        //   public void propertyChange(PropertyChangeEvent evt){
            //   try{
                //       verFechaRetiro();
                //   }catch(Exception e){

                //   }
            //   }
        //});

tabla.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {
        "Title 1", "Title 2"
    }
    ));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
            .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(90, 90, 90))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbttransmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbttransmisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbttransmisionActionPerformed

    private void rbtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtModeloActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbtModeloActionPerformed

    private void rbtGpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtGpsActionPerformed

    private void rbtBoosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtBoosterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtBoosterActionPerformed

    private void rbtSillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSillaActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_rbtSillaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        obtenerCantDias();
        adicionales();
        System.out.println(adicionales);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CbxOfiDevolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxOfiDevolActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_CbxOfiDevolActionPerformed

    private void rbtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAñoActionPerformed
        // TODO add your handling code here:
        if (rbtAño.isSelected()) {
            txtAño.setVisible(true);
        } else {
            txtAño.setVisible(false);
        }
    }//GEN-LAST:event_rbtAñoActionPerformed

    private void rbtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPrecioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbtPrecioActionPerformed

    private void rbtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMarcaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbtMarcaActionPerformed

    private void rbtEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEstiloActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbtEstiloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentaVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentaVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentaVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentaVehiculo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxOfiDevol;
    private javax.swing.JComboBox<String> CbxOfiRetiro;
    private javax.swing.JComboBox<String> cbxEstilo;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JComboBox<String> cbxModelo;
    private javax.swing.JComboBox<String> cbxTransmi;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateDevol;
    private com.toedter.calendar.JDateChooser jDateRetiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtAño;
    private javax.swing.JRadioButton rbtBooster;
    private javax.swing.JRadioButton rbtEstilo;
    private javax.swing.JRadioButton rbtGps;
    private javax.swing.JRadioButton rbtMarca;
    private javax.swing.JRadioButton rbtModelo;
    private javax.swing.JRadioButton rbtPrecio;
    private javax.swing.JRadioButton rbtSilla;
    private javax.swing.JRadioButton rbttransmision;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
