/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bo.VehiculoBO;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import entities.Vehiculo;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kendall
 */
public class reporteUsuacioaAsociadoVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form reporteUsuacioaAsociadoVehiculo
     */
    String imagen2 = null;
    public reporteUsuacioaAsociadoVehiculo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Vehiculo asocido a Usuario.");
    }
    public void reporteAsociacion() throws FileNotFoundException {
        String nombre = "Reporte Vehiculo asociado a Usuario.";
        try {
            Vehiculo vehi = new Vehiculo();
            vehi.setPlaca("JRM-026");
            VehiculoBO resultado = new VehiculoBO();
            imagen2 = resultado.imagenes3(vehi);
            if (imagen2.isEmpty() == false) {

                FileOutputStream archivo = new FileOutputStream(nombre + ".pdf");
                Document documento = new Document();
                PdfWriter.getInstance(documento, archivo);
                documento.open();
                
                Paragraph texto = new Paragraph();
                texto.add("Vehiculos alquilados por Rango de Fecha");
                texto.setAlignment(Element.ALIGN_MIDDLE);
                
                Image imagen = Image.getInstance(imagen2);
                imagen.scaleAbsolute(150, 100);
                imagen.setAlignment(Element.ALIGN_LEFT);
                imagen.setBorder(Image.BOX);
                imagen.setBorderWidth(4);
                imagen.setBorderColor(BaseColor.RED);
                documento.add(imagen);
                documento.add(texto);
                documento.close();
                //Esta parte abre el documento
                try {
                    File path = new File(nombre + ".pdf");
                    Desktop.getDesktop().open(path);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo abrir el documento. " + e);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se encontro el numero de cedula digitado. " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGenerarPDF.setText("Generar PDF");
        btnGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGenerarPDF)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnGenerarPDF)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPDFActionPerformed
        try {
            reporteAsociacion();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(reporteUsuacioaAsociadoVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporteUsuacioaAsociadoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporteUsuacioaAsociadoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporteUsuacioaAsociadoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporteUsuacioaAsociadoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporteUsuacioaAsociadoVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarPDF;
    // End of variables declaration//GEN-END:variables
}
